### ISSUE TITLE
Improvising leaderboard by adding more metric

### ISSUE THREAD

**Issue by gurumukhi** [mozilla/activate.mozilla.community#131]
Should we have more metrics on the leaderboard? lIke - tweets count (with hastag), instagram pics (with hashtag) count etc or any other kind of metrics.

**Comment by brianking** [comment]
Yes, we should!

**Comment by couci** [comment]
in order to do so we need to have different leaderboards. @MichaelKohler do you think we can implement this? For example a leaderboard tracking social media impression thus counting the reps that are doing social media work?

**Comment by MichaelKohler** [comment]
We probably could get the Twitter handle from the Reps portal. But that would further mean that we can only count Reps. For Instagram or other sources this might get trickier.

Also, this might get tricky, since all the computation is done client-side, so loading the page will take quite some time if we do that. We would need to check all Reps' twitter handles and their posts from date X until today and count them. This is some extensive power needed. We could save that in local storage so it would not need to be calculated at every page load, but at first-visit this could take waaay too long. There is no way to save that on our side with our current architecture. However we could also consider doing this somewhere else where we would have an API and could just get the data from there.

@AlexLakatos any other idea?

**Comment by nukeador** [comment]
Quick feedback: Please evaluate the effort here on improving the dashboard having in mind we want to transition activities next quarter to be more about "creating a network around X" rather just one time activity.

**Comment by MichaelKohler** [comment]
Thanks for the input here. We will discuss this issue over in https://github.com/mozilla/activate.mozilla.community/issues/210 as this is coupled to getting attendee data for now. Getting more metrics etc would be nice, but not a P1 right now. Also as we don't have a backend, we need to fetch all the data at every request, so getting much data won't be feasible as loading the leaderboard already takes quite some time.
