### ISSUE TITLE
Add Guidelines for Budget and Swag

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#21]
1) no swag being shipped except big events maybe (150+ attendees)
2) local production with budget is okay as long as it fits guidelines
3) swag only for events that have budget too

We could adapt and update https://wiki.mozilla.org/ReMo/SOPs/Swag_production and add

1) the kind of swag we want to support local production for
2) the guidelines on which activities we accept additional funds for swag production

In the end I guess this will be its own document (probably on activate.mozilla.org?) since it will be quite specific (nevertheless we should update the generic infos on the SOP).

India has an existing system for local swag we can use, and $2K leftover from a previous campaign.

**Comment by couci** [comment]
I think the missing piece here is what are the events we are supporting with budget/swag.
Once we have the list with those we can decide which will get local production, budget and swag from our vendor

**Comment by brianking** [comment]
:couci I'm not sure what you mean. Events, if it works out well, will be happening all the time. Do you mean further defined criteria?

In terms of what the events contribute to, we've already updated the portal for this, see issue #2.

**Comment by kelimuttu** [comment]
@couci you mean, what kind of activities, or which initiatives? 

and btw, I have question here. Is this guideline will effect the general budget & swag request? or will this only effect events that related to activity campaign?

**Comment by couci** [comment]
@brianking my question is on which of the activities listed on the issue you've mentioned will be sponsored by us. My thinking on how to proceed with this is the following:

1)Let's decide what activities will be sponsored (either swag or budget)
2)Let's decide which need budget, which need swag and which need both
3)Let's decide the limitations, on budget will we have a max amount, what cases will need local production and what need swag from our vendor, India specific cases.

In that way we will be able to create a clear guideline that won't confuse people and be crystal clear in advance

**Comment by Flore-mozfr** [comment]
Hi, just to give a community point of view. Swag seems very important for the communities, even for small events. And usually people complain they don't get enough, or too late, or whatever. I know it's hard to manage for you guys and also it costs a lot.
We would like that communities be trusted with a certain amount of swag that they could manage and use for different events during one year. We asked if it was possible a few years ago, but it was not.
Perhaps now would be a good idea to reintroduce this idea... But a bit differently. Like every local / regional community could ask for a budget once a year to produce their own swag and use it during their local events.

For example, in France, we would do something like that:
* Decide within the community which type of swag we want to produce
* Estimate the quantities we need for 2017
* Ask  quotes from vendors and submit them as a budget request
* keep some money to pay for sending the swag to local events if we can't find people to bring the swag
* Once the budget is (hopefully) accepted, order swag and keep it at a convenient place (presumably, the rep cupboard in Paris office).
* When an event is planned, send some swag for it.
* For bigger events (like 150+ attendees) ask swag from mozilla through regular swag requests.
* End of 2017: check what was used, what was left. Ask fo feedback, new ideas, what should be produced or abandoned. ask for quotes.
* 2018: submit a new budget request for local swag.

**Comment by couci** [comment]
Hey Flore,
I love the idea but let's keep in our mind that these guidelines are for activity campaign swag thus we need to estimate how much will be needed there.
I will love to keep this conversation going though, can you open a doc with your suggestion?

**Comment by Flore-mozfr** [comment]
Yeah right. @couci maybe you should create the doc in the mozilla google doc system and share it with me (my gmail is ok for that purpose). It would probably be easier than me creating a doc and sharing with whoever at mozilla wants access.

So back to activate.mozilla.org... I see a problem (and that is a recurring one, with reps budget and swag requests). Let's say an event is planned, 150+ attendees and a budget request is made. What happens when the budget request is denied or reduced or accepted very late (I have real examples in mind)?
* Event is cancelled: no need for swag. Everything clear
* Event is still happening with no budget: swag is even more needed.

We should ask from the beginning: will the event happen without budget. And then the swag request depends on the budget request or not.

It raises even more questions:
* Why ask for a budget if the event could be held without budget? Well money can make things better, reimburse transport for a speaker that will get more attendees, offer food to volunteers to thank them for the event.
* But those events which happen without budget, how do they do? Some cost really nothing: venue is free / sponsored by another company, volunteers come from nearby and don't pay for transportation. But the majority happen because people say "ok, don't bother with a budget request, it's only XX€, I can pay by myself.". But not everyone can afford that (especially not students).

So a budget denied is not necessarily a no-go for an event and it should be taken into account for swag request. So that there is no double penance : no budget AND no swag...

**Comment by brianking** [comment]
@geroter and I discussed this earlier today and we want to keep it simple and apply automatic budgets and swag orders (or budget or local swag). The amount would be around $200.

For anything larger than that, we'd make it very clear that the requests would go through the regular Reps process and all the pitfalls that go along with that, including that it might not be processed in time.

The plan is to write an FAQ entry for this, and then link to the entry from each activity.

**Comment by brianking** [comment]
Suggested FAQ Entry:

Q: Can I request budget or swag for these activities?

A. We encourage you to run these as lean as possible, but realise that sometimes there are some costs incurred for some refreshments or logistics for core organisers. If your event meets the  requirements laid out in the activity, there is a fund available of $200USD that can be processed quickly. For larger budget requests, it will be processed like any other Reps budget request and there is no guarantee it will be approved and even if so whether it will be on time. A portion of the the $200USD can also be used to create locally some materials for the event such as stickers. Assets to use will be included in some activities. Unless explicitly mentioned in the activity, there will be no other swag available for the campaign.

**Comment by couci** [comment]
Replying for both @Flore-mozfr and @brianking in this comment
@Flore-mozfr I agree that a budget request should not be a blocker for swag. But that again applies to all cases we have and I would like to keep the activity campaign as less complicated as possible. So in this case what I would propose is: the activity campaign doesn't have swag requests except if you have an event for over 150+ people. On those rare cases we will review the event as a whole and not as 2 parts (swag and budget).
@brianking I like the FAQ but I believe that the 200 USD is rather a big amount for countries like India for example. I would suggest 150 USD.
Proposal:
Q: Can I request budget or swag for these activities?

A. We encourage you to run these as lean as possible, but realise that sometimes there are some costs incurred for some refreshments or logistics for core organisers. If your event meets the requirements laid out in the activity, there is a fund available of $150USD that can be processed quickly. For larger budget requests, it will be processed like any other Reps budget request and there is no guarantee it will be approved and even if so whether it will be on time.
The 150 USD can be used for only the following items/services:
 * local stickers
 * list of services we agree on (hardware, food for events more than 5 hours etc).
 Assets to use will be included in some activities. Unless explicitly mentioned in the activity, there will be no other swag available for the campaign. 

In that way we set the expectations straight on what we approve and we won't have cases where people will add services since they have more money to spend.
Let me know your thoughts

**Comment by brianking** [comment]
I've updated the entry based on feedback:

https://activate.mozilla.community/faq#can-i-request-budget-or-swag-for-these-activities

@couci @Flore-mozfr @geroter please review. I took @couci 's suggestion, made and made some minor tweaks and made it clearer at the end on how to make the request.

**Comment by couci** [comment]
Looks good to me :)

**Comment by Flore-mozfr** [comment]
Looks good to me.
But I'm surprised by the "(in the case of the no other alternative)", shouldn't it be "there is no...".
Not sure though.

**Comment by kelimuttu** [comment]
Hi all, 
I see there's "meets the requirements laid out in the activity" part in the FAQ. Have we define the requirement somewhere? or am I the one who missed it?

**Comment by brianking** [comment]
@Flore-mozfr what that means is that venue rental should only be considered is there is no free option. Do you read it as meaning something else? Or are you proposing something else? If so, let us know what it is by filing a new issue.

@kelimuttu The requirements are not defined, but it should be possible to determine just by looking at the activity. If this proves not the be the case, please file a new issue. All in-budget (<150) requests should go through me for approval, and all over-budget (>150) should go through the standard Reps process with some input from me.

**Comment by Flore-mozfr** [comment]
@brianking I was just surprised by the grammatical form (never saw that before). Perhaps we should make it more simple like "if there's no other alternative" (same meaning but less confusing imho).

Just saying that because I'm one to write convoluted sentences and then read them again and not sure of what I meant anymore. So I'd say let's go for easier.

**Comment by brianking** [comment]
I've changed it to:

Venue rental (in the case that a free venue is not available)

Thanks.

**Comment by kelimuttu** [comment]
"meets the requirements laid out in the activity" sounds like we have define the requirement per activity. If the requirement you mean is the criteria for the <150 & >150 participants, then I think it will be better if we say directly that "if the participants is less than 150, you can request budget through the fast track process for up to 150 USD. But if you have more than 150 participants and you need more than 150 USD then it will go through the normal budget request process." That's just an opinion tho'

**Comment by umeshagarwal** [comment]
@brianking Just wanted to confirm that for India we are covering:
1) Locally produced Swag for Events happening in India - Coordinated by Umesh and Our Logistic team which includes (Chandrakant and Prathmesh)
2) Direct Fast tract budget which is less than 150 USD. Budget more that 150 USD will go through the usual process. -Coordinated by Umesh and Our Logistic team which includes (Chandrakant and Prathmesh)

Latest Notes:
- We will start producing Swags from this week with priority on: 
   -Empower developer communities( Dive Into Rust andWeb Compatibility Sprint) 
-Second week onwards we will follow the same process for the next topic:
   -Use and test experimental Firefox features and Maker Party

Swags we will be producing for each topic:
-Limited T-shirt, Round Stickers, Square Stickers, Lanyard, Buttons, Brochures.
-Separate Swag pack for seperate topics. 
-We will use our own form and Keep @brianking as reviewer including us(Logistic Team).

Swag Pack:
- 10-50 Participant -> (One T-shirt for Organizer, 50 Round Stickers,  10 Buttons, 10 Brochures, 5 Lanyard).
- 50-100 Participant -> (Two T-shirt for Organizer, 100 Round Stickers,  20 Buttons, 20 Brochures, 10 Lanyard).
- 100-150 Participant -> (Three T-shirt for Organizer, 150 Round Stickers,  30 Buttons, 30 Brochures, 15 Lanyard).
- 150-300 Participant -> (Three T-shirt for Organizer, 250 Round Stickers,  50 Buttons, 50 Brochures, 20 Lanyard). 

Courier/Packing&sending:
-We are partnering with a cheap vendor who will do the packing and take care of sending it though out India. 

I already have 2000 USD which is okay for producing the swags for the whole campaign.
But for budget for events we will need funds allocated to us based on your priority of how much you want to allocate and how many events you are expecting through out the event.

@brianking Let me know if you have any question!

Regards
Umesh Agarwal

**Comment by kelimuttu** [comment]
Hi @umeshagarwal , 

is that mean that India will have a special process for mozactivate event? Is this has been finalized? Several mozactivate request has been popped up right now, so having the discussion together will be better, I think.

**Comment by umeshagarwal** [comment]
It was partially approved for swag. I will wait for @brianking to approve for budget as well. I think we should not hold events which are close but next week starting we will have a separate process for India.

**Comment by kelimuttu** [comment]
Okay, the only suggestion I have is to keep me and @couci in the loop of the discussion as we're tightly involved in the process. 

And actually, I was thinking that this is a very good idea. India is one of the most active community, so having the local swag inventory will help a lot to reduce budget. Look forward to hear more update from @brianking

**Comment by umeshagarwal** [comment]
Yes that is the reason i have not started any mail thread and adding all updates directly on this issue. :) 
Yes local inventory will actually save 50% of budget for overall expenditure on swags  and shipping.

**Comment by brianking** [comment]
Just chatted with Umesh. I am going to create a new issue just for the India process and we can document and discuss there.
