### ISSUE TITLE
Add metrics on Event Page of Mozilla Reps Portal

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/activate.mozilla.community#27]
I think it's important to add metrics related to Mozilla Activate on the events page, this facilitates registration and measurement of the results generated by events.

**Comment by MichaelKohler** [comment]
Thanks for this issue. As I currently see it from the published activities, we could have the following metrics:

* MozActivate - TestPilot add-on installs
* MozActivate - TestPilot shares
* MozActivate - Web Compatibility add-on installs
* MozActivate - Web Compatibility issues filed
* MozActivate - Signups to the Web Compatibility list
* MozActivate - Developers who will write in Rust in the next months
* MozActivate - Signups to the Rust developer list

As with the other metrics we have in the Portal, it's not easy to fill it out instantly since it needs followup to make sure that it happened if there is something to be done after the event by the participants.

@brianking what do you think? Is there any other way planned to track the impact on the goals?

**Comment by brianking** [comment]
Most of these we can track separately. For example, add-on installs can be tracked on the AMO site, and we can even check the referrer to see if it is coming from our site. We can also track social shares. I don't think it is feasible to track that one at an event.

What is important about logging your activities on the portal is that it should tell us what our mobilizer strength, i.e. the number of people leading events/activities. For more details see:

https://activate.mozilla.community/faq#what-are-the-goals-of-the-campaign

**Comment by barrosgeraldo** [comment]
@MichaelKohler, awesome! I think that the metrics are perfect, it is important to add on the page events of Mozilla Reps, because representatives can log the results of the event.

**Comment by brianking** [comment]
@barrosgeraldo see my previous comment. For now, we are going to keep the metrics on the Reps portal to a minimum because we can track other things elsewhere.
