### ISSUE TITLE
Add SUMO Days as Active Campaign

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/activate.mozilla.community#323]
URL: https://events.mozilla.org/firefox66supportsprint
Title: Firefox 66 SUMO Sprint
Date: March 19 - April 2 2019
Description: Join the SUMO community through supporting Firefox Desktop and Firefox for Android users. Let's save the world from behind the comfort of your computer!
Image: 
![Screenshot_2019-03-13 Firefox 66 SUMO 2 Week Sprint](https://user-images.githubusercontent.com/4922388/54273027-838e8d00-45b7-11e9-884b-5186108d1973.png)

**Comment by MichaelKohler** [comment]
Would it make more sense to just use a firefox logo? Screenshots as images can be confusing and there is too much info on it destracting from the real info right next to it.

**Comment by kelimuttu** [comment]
Sure. We don't have any specific logo anyway.

**Comment by MichaelKohler** [comment]
I'll make a PR with the Firefox logo and let you review it. And I'll post a screenshot there how it would look like with the image attached above, so you can decide :)

**Comment by kelimuttu** [comment]
sure. Thanks! (:

**Comment by couci** [comment]
Hey both,
thanks for your work. By looking at this again could we make some small changes?
I would suggest ochange the picture with something like: https://static-media-prod-cdn.sumo.mozilla.net/static/sumo/img/gi-hero-butler.png

Also we should have a description under the title, proposal: Join the community through supporting Firefox Desktop and Firefox for Android users.

Last thing, since not all of people that will see this will know what SUMO is, I would suggest to change the title to : Firefox 66 Support Mozilla (SUMO) Sprint. That way people will know instantly what this is about

@MichaelKohler want me to open another issue, or tracking things here is fine?

**Comment by LucyeoH** [comment]
Hey @couci any reason we didn't use the new template for this campaign? https://events.mozilla.org/activateeventtemp

**Comment by kelimuttu** [comment]
FYI @couci I made a new PR for this changes https://github.com/mozilla/activate.mozilla.community/pull/326

**Comment by MichaelKohler** [comment]
This is already in production, as it's already better than before. @couci if you have any other requests, add them here. Otherwise close this one :)

**Comment by couci** [comment]
@LucyeoH since we had to follow the SUMO event template we preferred not to use the campaigns template
