### ISSUE TITLE
Roadmap following "now-next-later"

### ISSUE THREAD

**Issue by hmitsch** [mozilla/activate.mozilla.community#33]
# Job Story
When **looking at the Activate roadmap**
I want to **understand which community campaigns are in the making**
So I can **plan my time**
~~So I can **discuss the next hot things in my community**~~

# User Story
_Credit to @MichaelKohler for mentioning the story in https://github.com/mozilla/activate.mozilla.community/issues/33#issuecomment-240251366_

As a **volunteer** 
I want to **see a clear roadmap on how things are expected to work out**
in order to **plan my time**

# Acceptance Criteria
- URL: https://activate.mozilla.community/roadmap
- Motivation: We move away from dates (because this does not allow for agility), while still providing a clear picture on what our functional commitments are.
- Roadmap categories
   - **Now** (We are working on that)
   - **Next** (We plan to do that next; late Aug and Sept pieces go here)
   - **Later** (We currently think that this is where we are going)

# UI Mock-Up
Now | Next | Later
---- | ---- | ----
Dive Into Rust (Rust and Servo) | e10s Add-on Compatibility (Developer Engagement) | Kittens on Mars
Web Compatibility Sprints (Developer Engagement) | Copyright petition (Privacy and Policy) | Translate the History of Mozilla into emoji
Test Pilot Install (Test Pilot) | Maker Party (Privacy and Policy) |

# Further Reading
- From _The Master_ (Roland Pichler): http://www.romanpichler.com/blog/10-tips-creating-agile-product-roadmap/ , see tip no. 7 _Know When to Show Dates_
- Light reading: https://www.prodpad.com/2016/02/how-to-build-a-product-roadmap-everyone-understands/
- And a last one: https://medium.com/@noah_weiss/now-next-later-roadmaps-without-the-drudgery-1cfe65656645#.mqw3r5ppf

**Comment by MichaelKohler** [comment]
I love this! I really like the "Now", "Next", "Later" concept. For many projects within mozilla I know about the "Now" piece since I most probably follow the relevant channels, might know about the "Next" piece due to discussions, but what I'm really missing is the "Later". This could be either in terms of we don't know either what "later" is, or we focus too much on the "Next" part and basically define it as "later" since there is too much scope in it and therefore gets pushed out. But it is still not "Later" in terms of "if we're doing it right, this is where we'll be".

Yay, I have the possibility to challenge Henrik :D While you're saying "because this does not allow for agility" you would put "late Aug and Sept pieces" in the "Next" piece. Of course we're not working in a customer relationship here, but I'm not sure if you mean to put the topic there, or put the topics there with the specific "late August"/"September" label. For the former I'd agree after reading your links, for the latter I'd be curious on the reasoning. According to your third link Foursquare defines #next as "1–3 months out" while not giving an exact point in time. Therefore my question ;)

From your second link from prodpad.com: "The point is to leave room to adjust to change. If something was current, but now you want to push it back, you can."
This stroke me pretty hard. While this can be done without (your first link, point 7 regarding dates) clear communication of the "when" towards external persons - and might work in the traditional "provider" <-> "client" scenario - I'm not sure if this works for mozilla. How would we define when to push and when to push with a clear timeline to make sure that contributors can plan their activities? As you might notice my comments are quite different depending which setting we're talking about. As a volunteers I'd like to see a clear roadmap on how things will work out and therefore I'll be able to plan my time - while still understanding that it's not easy to put an exact date on everything.

Let me come to a conclusion here and let me put a question into the room: can we make sure that volunteers can plan their time instead of just knowing that it's "coming soon" while still being able to act agile and change plans?

**Comment by hmitsch** [comment]
@MichaelKohler thanks for the intense study of the referenced links.

## Actionable Feedback
- Job Story updated
- User Story added

## Philosophical Feedback
With most of my answers I am harshly invading @nukeador and @brianking's area of responsibility as they are owning that amazing piece of work. Independent of that, I'd like to offer my agile product management perspective. However, I am totally open to be overridden by @nukeador and @brianking.
- **Paragraph 1:** I don't think that "_Later_" and "doing things right" should have a causal relationship.  It is in the nature of things that we are resource constrained. Now-Next-Later expresses intent and prioritization. As insight grows, scope items might go back and forward from _Later_ to _Next_ and vice versa.
- **Paragraph 2:** I would NOT mention dates ("late AUG/early SEPT) in the Next section, as it would defeat the purpose of moving from date-based deadlines to a more flexible (and truthful) expression of priorities. 
- Also, I would not be bothered to define whether or not we have a customer <-> service provider/agency/vendor relationship here. The Participation Team is serving and servicing a wide range of stakeholders, the Mozilla community being one of them.  
- **Paragraph 3:** At a maximum I would add date-based deadlines to scope items in the _Now_ column. This should provide contributors with robust planning assumptions for their _Next_ activities.
Not sure if this is an answer to the points you make in this paragraph? Please let me know.
- **Paragraph 4 (aka final question):** Yes, totally! If volunteers want to create robust plans, they need to rely on the _Now_ activities. If they are willing to take a bet on the future they can consider preparing _Next_ (low risk) or even _Later_ (high risk) scope items.

Looking forward to your feedback, @MichaelKohler.

**Comment by hmitsch** [comment]
PS: I just added a **UI Mockup** to the issue description. This might help to better understand the proposal.

**Comment by MichaelKohler** [comment]
**Paragraph 1:** yes, indeed, this was badly phrased. What I meant is, that we're focusing too much on the "Next" and don't really see what we should be focusing on in terms of what is "Future" that might be the most benefitial case in the current situation. We're mostly defining "Next" as "Future" because there is no "this is where we are going". My bad!

**Paragraph 2:** perfect, wasn't sure if I was getting you right. In the end, this conflicts with the initial User Story I wrote in that case. This basically means "sometime in the future, not too far from now though", but in that specific example here not knowing if it would be end of August or end of September, since that would still be in the margin of error.

**Paragraph 3:** "Also, I would not be bothered to define whether or not we have a customer <-> service provider/agency/vendor relationship here."  --> that's what I wanted to compare to, not what I'm defining for Mozilla. The point I wanted to make is that this is exactly **not** what we are working towards. And since the Participation team has a lot of stakeholders the question is where do we want to say **rough** dates and when not? What would "internal" mean in our case?

Further to that point: date-based deadlines for the "Now" sounds great to me, this is plan-able even though really short-term. Probably more like "until then I have something" instead "I can make sure that I plan 1 month ahead with my event and it will still be relevant". However, while it would enable contributors to have assumptions about their planning, in the reality it's really hard to adjust planning for activities on a short-term in case there is a plan change. My point being here is that contributors might want to wait for something that is defined in "Next" because it's their strength, but have no idea when this will be and therefore activity-planning is hard to do. I would imagine that a clear plan would be there once that point would be in the "Now" phase which would mean around 1-3 weeks to plan anything if you want to be at the start of it.

**Paragraph 4:** okay, I should have read your comment to the end before replying instead of doing it paragraph by paragraph. So, I'd say my comments above are more general than this campaign - while I still think it is relevant.

If we want people to focus on the "Now", I think we're pretty well set. Those activities won't disappear within the next few weeks. Also I agree, it wouldn't matter what comes next if you're interested in those. But let me do a thinking experiment here (experiment to follow without real hypothesis, therefore more like a question?):

Scenario 1) I'm interested in the "Now" activities, I'll do an event to get soooo many people do follow my example to educate their fellows about these activities. I need time to do this. Let's say it takes 1 month to prepare. This is not too bad since it something goes bad and we change shift, I can still cancel my event. But what about actually doing the event? The thing that comes to mind here is the budget process. Under $150 it goes through Brian according to the current proposal. While I completely trust Brian's skills, what tells me that in 2 weeks he won't be overwhelmed with these kind of budget requests and it won't happen in time? Okay, maybe I need to postpone it. Am I still in the "Now"? I don't think we want to sunset activities over time in this campaign here, but nevertheless, what happens if there is a sunset and we shift focus within that period? What if we decide that the "Next" focuses on something completely different which is better than what we had in the "Now"? This scenario is pretty okay since we just can say "nope, this won't be happening, we're sorry".  While the organisator of that activity would be sad, it wouldn't be a full loss and the organisator could focus on what is "Now" at that point. (DId I just create a circle here?)

Scenario 2) This scenario seems more important to me personally. What are we doing with people that are not interested in the current activities, but rather would like to contribute to Servo (which is apparently launching soon according to the website). As of now, as a person interesting in Servo, I know that it is "coming soon". What am I gonna do now? Developer Engagement is part of the currently available things, sure why not. But what if my thing is Servo and Servo only? I'd have an amazing opportunity to bring Mozilla forward, but as of now, I don't have any idea on when my service would be of pleasure. Can I organize an event that will take place in two month? Certainly yes, since it most probably will still fit Servo's goals. Will it fit the campaign's goals though? By extend I'd say yes, but as it is now (without knowing the Servo part of the community to be honest!) I might not know what might be most beneficial to the project. I might be a core contributor, but still wonder if more core contributors like me is what the project needs.
Stepping out of that role: I, Michael the guy who doesn't know core Servo stuff, know that it might be more benefitial to test popular website in the engine and report and fix those bugs. But how can I plan for this? That is certainly something that is in the "Next" and in the end I might give my best try for it as you say.

My point basically: can we get a really basic explanation of the "coming soon" activities so we can at least get the direction the activities are going towards so we can plan for it? Somebody's interpretation of "Support the future Mozilla Web engine (coming soon)" might be waaaaaay different to what I would know about it, so how can we make sure that we point willing people into the right direction now instead of a few weeks before it gets relevant? This would enable us to plan ahead and at least **guess** what those "low risk" or even "high risk" activities will involve. In the end I think all mozillians want to reach the point of having the most impact and most fun on what their doing. Let's combine those two and make it less risky!

@hmitsch personal question, could you please give me feedback on this answer regarding understandability? This is really long and I'd love to hear your feedback on how I could have expressed myself shorter! For that let's not use this issue but instead Telegram or e-Mail, you know the coordinates :)

In general, thanks for the links in the initial description, I've already learned a lot and I'm sure I will learn a lot more with this conversation!

Cheers,
Michael

**Comment by MichaelKohler** [comment]
Quick addition: while an activity that is not fully aligned might not have the desired impact, it still could have some impact that brings us forward. That is what we would define as "risk" as Henrik answered. The table in the initial description now says "Copyright petition (Privacy and Policy)" (thanks for the table!).

But what does that mean? Is it in Mozilla's interest that I'm doing an activity which is promoting downloading movies in Switzerland without upload which is fully legal? That would cover the current copyright issues discussed on a global level pretty well.  On the other hand I'd see the reactions to that, "Mozilla doesn't want movie producers to earn their well deserved money". So let's focus on the "(Privacy and Policy)" part. To be completely honest here, I can't connect privacy with copyright in any case apart from DRM, which in itself as I understand it, is not a privacy issue per se. Policy, sure, Copyright is a policy issue in terms of legislative structures. So should I take the "low risk" (as you said because it's "Next") and go for a gut feeling even though I might combine them in a weird way and not represent our view point on it? I know that this scenario is completely over-exaggerated, but I honestly can't come up with anything else.

**Comment by nukeador** [comment]
I haven't read all comments here in detail but I like the concept. I would add that some people like more precision on what Next and Later means. Could be 1 month or 1 year ;-)

**Comment by hmitsch** [comment]
@nukeador,
totally understand your feedback. The idea would be:
**Next** is something that we consider the "near enough future" to keep an eye on. 
**Future** is everything beyond that. 

In case of the Activate campaign I suggest:
**Now**: this quarter (i.e. it is in our current OKRs)
**Next**: probably next quarter (i.e. from today's perspective we feel comfortable adding this to next quarter's OKRs)
**Later**: everything beyond next quarter's OKRs. This is not even in our half-year plan yet. It is a potential future we cannot commit to from today's perspective.

Does this make sense?

**Comment by nukeador** [comment]
"Now" meaning this quarter could be confusing since we'll have things that are active right now and others that won't be available until the end of the quarter (in +2 months).

**Comment by hmitsch** [comment]
Makes sense. Maybe we are confusing things? This is about the roadmap document. Things that are already active should not be put into the roadmap. What do you think?

-- 
Henrik Mitsch

**Comment by nukeador** [comment]
I see... that's the confusion, for me "Now" includes what's happening now. @brianking ?

**Comment by brianking** [comment]
@hmitsch 's logic makes sense to me, even though I can see why it can cause confusion. I would be in favour of using Now/Next/Later once we can make it clear in the intro that Now means 'planning now'.

**Comment by brianking** [comment]
Roadmap has been updated.

https://activate.mozilla.community/roadmap/

Assigning to @comzeradd to apply some CSS love to make it look prettier, then we should be done and it will be easier to update when we have new activities in the pipeline.

**Comment by MichaelKohler** [comment]
@comzeradd that already looks better, thanks! Since the page is pretty white, I think (and this is highly subjective of course) that having a colored header would be more appealing, what do you think?

![screen shot 2016-10-05 at 15 25 24](https://cloud.githubusercontent.com/assets/330324/19114874/1772426a-8b10-11e6-9a7a-22a08824013d.png)

**Comment by brianking** [comment]
@MichaelKohler Please file new issues for bugs or requests.
