### ISSUE TITLE
Enable pontoon in-context localization

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#337]
This will help people who want to focus on sections like homepage or a specific activity, rather than the whole set of strings

https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website#B._(optional)_Enable_in-page_localization_of_your_web_project

/cc @peiying2 in case we need something else on pontoon side once this is deployed.

**Comment by MichaelKohler** [comment]
I've included the Pontoon script and deployed. However, we will need to change the X-FRAME-OPTIONS header before it will work, I'm looking into that.

Here's the full list of sub URLs we have. All of these links also exist without a locale path, for example: https://activate.mozilla.community/commonvoice. However, when going to that page, every subsequent link will lead to /locale/whatever. Hope this doesn't break, otherwise we need to disable that and only do it when there actually is a locale in the URL anyway.

https://activate.mozilla.community/en-US
https://activate.mozilla.community/en-US/commonvoice
https://activate.mozilla.community/en-US/nightly
https://activate.mozilla.community/en-US/techspeakers
https://activate.mozilla.community/en-US/webextensions
https://activate.mozilla.community/en-US/rust-hack
https://activate.mozilla.community/en-US/webvr-camp
https://activate.mozilla.community/en-US/webcompat-sprint
https://activate.mozilla.community/en-US/campaigns
https://activate.mozilla.community/en-US/activities
https://activate.mozilla.community/en-US/faq
https://activate.mozilla.community/en-US/eventguide
https://activate.mozilla.community/en-US/newsletter

**Comment by MichaelKohler** [comment]
Instead of going for the infra PR, I've asked nemo directly to change the X-Frame-Options header for the website so we can move forward here.

**Comment by MichaelKohler** [comment]
I've talked with nemo and it would be quite complicated to make sure we can set that header, as GitHub Pages overwrites them. We would need him to implement custom behavior and therefore need his time. There are more important things to do, so I will put this in the backlog.
