### ISSUE TITLE
Activity titles string include emoticon

### ISSUE THREAD

**Issue by lissyx** [mozilla/activate.mozilla.community#356]
The string includes the emoticon, while it should not.

![Screenshot_2019-06-13 Contribute to Common Voice Activate Mozilla](https://user-images.githubusercontent.com/1645737/59439891-56d85480-8df6-11e9-9207-92cad78f96c3.png)

**Comment by MichaelKohler** [comment]
Is there a specific reason why they shouldn't be? I could image that the clown could not be a very good icon in some cultures and this would allow to change it for specific locales.

**Comment by lissyx** [comment]
@MichaelKohler Well, @nukeador said that on Slack and suggested to file a bug for it :-)

**Comment by nukeador** [comment]
@MichaelKohler Having this into the localization interface is confusing and some locales removed the icon by mistake. Since this is a design decision I think for now it should be outside the strings, if one icon is problematic we can tackle that for all locales and find a better solution to fir them all.

**Comment by MichaelKohler** [comment]
Here's my take on it:
* Some locales do not have it (either due to confusion or deliberately) - for example fr
* Some locales opted to change the emoticons - for example ru
* Generally I'd say the emoticons as well as the text should be internationalized - not just translated. I'm sure there are several locales where "ranger" does not make much sense and there would be a better word and there would also need to be a new emoticon going with that.
* I'm not sure how we handle that generally at Mozilla in terms of "just localizing whatever there is" vs. "make it work best for your locale while still having the same broad meaning".
* I'd suggest to keep the emoticons part of the string and therefore having the possibility to let communities decide what's best for their locale. I'd personally also be fine with it if locales decide to remove them.

@lissyx also interested in your take on my thoughts here.

Over to @couci for evaluation and decision. Please assign to me if we need to change anything and I'll do it.

**Comment by lissyx** [comment]
> @lissyx also interested in your take on my thoughts here.

I don't really have an opinion here, I just stumbled upon the fact that it was missing, when I was working to localize it more (work has been started).

I'd think doing i18n on them makes sense, any opinion @TheoChevalier ?

**Comment by TheoChevalier** [comment]
> > @lissyx also interested in your take on my thoughts here.
> 
> I don't really have an opinion here, I just stumbled upon the fact that it was missing, when I was working to localize it more (work has been started).
> 
> I'd think doing i18n on them makes sense, any opinion @TheoChevalier ?

Yup, totally agree to @MichaelKohler’s take above, I’d advocate for either this (i.e. keeping them as part of the string) or removing them altogether, and can confirm the theory for French — it was a deliberate omission, because we transcreated the copy and the new copy in French didn’t match the original meaning of the English copy anymore. We also felt the use of emoticons here wasn’t a great fit in French, as we usually tune down the tone compared to English.

**Comment by couci** [comment]
I think we should keep them in the string and give the freedom to locals to remove them or change them as they see fit
