### ISSUE TITLE
Extra event localized material

### ISSUE THREAD

**Issue by lissyx** [mozilla/activate.mozilla.community#360]
As part of holding some events for French Common Voice, and thanks to Taiwanese Community member, we have some other material (namely different posters, business cards) that is localized and that can be of help for anyone wanting to host an event. Having a way to share / link from from Activate page would be great.

**Comment by MichaelKohler** [comment]
@couci thoughts? How should this look? Doing it per localization might be tricky.

**Comment by lissyx** [comment]
If we can get a localized link for extra material that might be enough and we can link to our github account for example ?

**Comment by MichaelKohler** [comment]
@couci Nuke is suggesting instead of linking to specific documents to just link to one single folder for every language. Then we can put localized files in there. This would include the currently linked slides for Common Voice for example, as well as possibly other documents that would be added to the folders.

**Comment by couci** [comment]
I think having a folder makes sense. @lissyx what graphic material did you use? I would like to pass it first by Megan before we make them available to the whole community
