### ISSUE TITLE
avoid using zh-CN as localization fallback for zh-TW

### ISSUE THREAD

**Issue by petercpg** [mozilla/activate.mozilla.community#362]
I think this might be a issue at the l10n library side, but please directly use English as fallback, when string is missed in zh-TW localization, instead of using zh-CN strings.

That is, expected: zh-TW -> en ; actual: zh-TW -> zh-CN -> en .

**Comment by MichaelKohler** [comment]
I *think* we do not have any preference there, however it might be that fluent (the framework we're using) does. I could imagine it falling back through the "cn" identifier and then back to EN. I'm on my phone right now so hard to say.

@Pike @stasm thoughts here?

**Comment by stasm** [comment]
It looks like _activate.mozilla.community_ uses `fluent-langneg`, which is our recommended language negotiation library built upon the [RFC4647](https://tools.ietf.org/html/rfc4647). Falling back on other regional variants of `zh` is a _feature_ of the algorithm. I understand that there are reasons to bypass it in some cases. Unfortunately, we don't support any way to do it right now.

@zbraniecki : Would it make sense to consider adding an option to `negotiateLanguages` to allow overriding certain fallback chains?

**Comment by zbraniecki** [comment]
The idea of language negotiation is to facilitate custom fallback chains and fallback on "default" ones in the absence.

In that case, I'd expect the user to specify their preferred language fallback chain to be `["zh-TW", "en-US"]`.
Otherwise we have to try to rely on the data we have. If the user asks for `zh-TW` we can deduct using likelySubtags[0] that their locale is `zh-Hant-TW`, but then when we match it against `zh-CN` which does not have a likely subtag extension, it'll still be treated as `zh-*-CN` rather than `zh-Hans-CN`.
I looked at matching languages data in CLDR and I'm not sure if there's a good way to algorithmically recognize that TW should not use CN as a fallback.

I'll ask Unicode about it.

[0] https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/likelySubtags.json

**Comment by MichaelKohler** [comment]
@zbraniecki is there any update here? :)
