### ISSUE TITLE
Activate -> Portal Transition Notice

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#382]
As part of the comms plan, we need a banner on the site talking about the end of life and what's going to happen in March:

`Attention: The Activate website will be closing in March 2020 as all our campaigns and activities migrate over to the new Community Portal. Starting in April this url will <a href="https://community.mozilla.org/">redirect you to the portal</a>.`

Thanks!

**Comment by nukeador** [comment]
cc @LucyeoH 

I know @MichaelKohler had some feedback on the copy there.

**Comment by LucyeoH** [comment]
@MichaelKohler What are your thoughts? Here's a revised version. 

Attention: All of the Activate content will be migrating to the new Community Portal in March 2020. Starting in April this url will <a href="https://community.mozilla.org/">redirect you to the portal</a>.

**Comment by MichaelKohler** [comment]
I feel this does not provide much value. While the user will know there is something happening, the user does not know what this means for them. In effect, I feel the user does not even care about this, as there is will be a redirect anyway. And for these who care and we want to keep informed, the banner does not provide any value as they do not know what will happen exactly, as there is no preview on the Community Portal.

So I'd suggest the following:
* Link to a FAQ (can be the one on Discourse) at the end of the message
* Extend FAQ to tell what will be the same / different for Activities and Campaigns - such as localization not being possible for now, maybe activities that won't be transfered, etc..

@LucyeoH  What do you think?

**Comment by LucyeoH** [comment]
@MichaelKohler I guess the thing is that b/c all of the content is being transferred it's going to make a huge difference to most people. It's also why I don't want to call it "killing activate" since it's much more of a "migration". The activities and campaigns will even look very much the same and all the old campaigns will still be there. I like of adding the FAQ though. What about...

Attention: All of the activities and campaigns from Activate will be migrating to the new Community Portal in March 2020. Starting in April this url will redirect you to community.mozilla.org. If you have any questions checkout the FAQ [here](https://discourse.mozilla.org/t/frequently-asked-questions-portal-edition-faq/43224).

**Comment by MichaelKohler** [comment]
Thanks, and thanks for updating the FAQ. That now provides way more value. This will be live in a few minutes.
