### ISSUE TITLE
Recruit and Equip Mentors and Regional Coaches to Mobilize Mozillians

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#44]
Initial items:
* [ ] Create short blurbs on how to get involved
* [ ] Clarify about how, and why, Reps should run the activities

OUTPUTS:
* [ ] Email to send to mentors/coaches
* [ ] Document with talking points, tips, tools, ...

**Comment by MichaelKohler** [comment]
Hi Brian

I think involving Mentors and Regional Coaches to mobilize Reps in the campaign is a good idea. However I'm not sure if I get those checkboxes correctly. I don't think Mentors or Regional coaches need talking points, I think we need to solve this on the website level. Mentors and regional coaches should be able to say "hey, in case you've missed it, here is a website with an activity that seems to be tailored for you perfect, how about you getting out there and mobilize your local community?"  I really hope that all mentors at least know their mentees' interests and therefore can go out to them and point them into their probably most favorite direction regarding this campaign. 

If we need talking points, I'd suggest to look at the website again and make sure that it is clear enough so Reps (and Mozillians in general) would want to get involved instead of having the need to get pinged by their mentee or a regional couch with specific points on why they should get involved to know why they should get involved if they've seen the page before. I think the website should be clear enough to make this issue obsolete apart from the reminder to get in touch with the mentees/coachees about it. There might indeed be people who have missed this announcement and this way would be a good one to make sure to remind them about it.

Please tell me if I understood this issue wrong since there are some missing words (at least after the second checkbox).

Cheers,
Michael

**Comment by brianking** [comment]
Thanks for the input Michael. I agree that more guidance is needed on the site and the activities need to be presented in a more compelling way (for everyone, not just Reps). We've opened other issues to tackle that.

The main reasons for the Reps connection here with mentors/couches is:
* to act as a reminder
* to express why the campaign is important why it aligns with Reps in general

**Comment by brianking** [comment]
Going to merge this one into #42
