### ISSUE TITLE
Rust Swag Experiment

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#48]
Experiment with creating some premium Rust swag for distribution to event organisers and/or at events.
- [x] Have initial conversation with Brian Anderson and @couci 
- [ ] Get estimates for local swag production
- [ ] Create and agree on a distribution model
- [ ] Track impact

**Comment by brianking** [comment]
From @brson:

FYI I've opened a thread on the Rust forums summarizing the state of Rust swag and suggesting ideas for future work: https://users.rust-lang.org/t/all-the-rust-swag/7036

**Comment by couci** [comment]
After a talk we had with Brian here is our strategy:
 * we will build local swag in Berlin and India. That will be stickers and t-shirts with the design provided from the Rust team
 * we will produce stickers and t-shirts in our central US vendor. That will help us ship around the globe.

Quantities to be added

**Comment by brianking** [comment]
Chatted with @couci ...

\+ @kelimuttu who is helping coordinate on:

> - first we want to work a standard procedure for local communities to produce swag
> - then we will work on artwork

**Comment by kelimuttu** [comment]
@brianking I see most of the design in https://users.rust-lang.org/t/all-the-rust-swag/7036 are for commercial purpose. Don't you think we need our own design for communities?

**Comment by brianking** [comment]
I'll defer to @brson here. I believe the community has a discussion about designs, but didn't reach consensus. We might need to call in some design help. Brian?

**Comment by brson** [comment]
@kelimuttu I do think it would be best to get a fresh design, mostly because all the ones in that thread are old and not that inspiring, but you are welcome to use any of the designs in that thread. The most popular one there is the [rustacean shirt](https://teespring.com/rustacean-two#pid=370&cid=6543&sid=front).

Every few weeks in the Rust core team meeting we discuss commissioning a new Rust t-shirt, but so far there is no movement on it.

I would not rely on unpaid contributors to produce a useful T-shirt for this purpose. Either the Rust team should commission something, or Mozilla's in-house designers should create something. But seeing as the Rust team has not been able to make headway on this for months, I would suggest not counting on us either. I will bring it up to the Rust core team yet again this week.

It's frustrating.

**Comment by kelimuttu** [comment]
@brson Thank you for bring up this to the Rust team. I understand the situation. And btw, if you haven't heard, we have Open Design team where we can file design requests for the community design group. They also help us to create special stickers for Activate Mozilla initiative. You can take a look on their repo https://github.com/mozilla/OpenDesign/

What do you think if we ask for help from them to create the Rust t-shirt?

Also, in the mean time, as you said that we can use those designs.. Do you know where we can get the hi-res and/or vector artworks of them?

**Comment by brson** [comment]
The Rust team has asked our designer to start work on a new Rust design, so we do have one underway now. I don't have an ETA on when it will be complete.

I've been reluctant to use open design based on their prior output and the size of their backlog.

The SVG Rust logo is https://github.com/rust-lang/rust-www/blob/master/logos/rust-logo-blk.svg

The source for the Rustacean design is http://www.rustacean.net/

**Comment by kelimuttu** [comment]
Alright. Then just let us know once it's completed. Also, thanks for the links.

**Comment by brianking** [comment]
Image files pending from @brson for new design.
